### PR TITLE
Added JSON Loader

### PR DESCRIPTION
**Pull request by pascalknecht**
Hi Alain
I added a JSON loader here since I need one in my current project.
Let me know what you think about it.

### CODE REVIEW

**Comment by pascalknecht** [comment]
Hey @schlessera . Any updates on this PR?

**Comment by schlessera** [comment]
Sorry, @pascalknecht, must have missed the notification.

**Comment by schlessera** [comment]
I've just merged this, I'll tag a new release for this change for you.

**Comment by schlessera** [comment]
Release v0.4.11 was tagged: https://github.com/brightnucleus/config/releases/tag/v0.4.11

**Comment by schlessera** [comment]
Thanks for the PR, @pascalknecht !

**Comment by pascalknecht** [comment]
Thanks for the update!

**Pull request merged**
